### ISSUE TITLE
Great blog post!

### ISSUE THREAD

**Issue by urish** [kennedn/kennedn.github.io#1]
Just found and read [your recent blog post](https://kennedn.com/blog/posts/snowdon/
). I love the level of detail, the clear diagrams and the deep dive into PIO (with the cool animation).

Thank you!

**Comment by kennedn** [comment]
Wow thanks Uri! Funnily enough that blog post would never have manifested without your amazing [RP2040 hackaday series](https://www.youtube.com/watch?v=OLV-TSRTTE8). It got me started on my PIO journey :smile:
